In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [21]:
import pandas as pd

# Load the dataset
file_path = '/content/drive/MyDrive/Colab Notebooks/Emigrants by Country 1981-2022/Emigrant-1981-2022-MajorCountry.xlsx'
df = pd.read_excel(file_path, header=None)

# Select specific rows and columns, then combine and clean headers
df = df.iloc[2:46, :12]
headers = df.iloc[0].fillna('') + ' ' + df.iloc[1].fillna('')
headers = headers.str.strip().str.replace(' ', '_')
df.columns = headers
df = df.iloc[2:].reset_index(drop=True)
df.rename(columns={df.columns[0]: 'Year'}, inplace=True)

# Reshape the data to long format
df_long = df.melt(id_vars=['Year'], var_name='Country', value_name='Emigrant_Count')

# Convert 'Year' column to numeric, ensure 'Emigrant_Count' is integer, and fill in nulls/blanks with 0
df_long['Year'] = pd.to_numeric(df_long['Year'], errors='coerce')
df_long['Emigrant_Count'] = df_long['Emigrant_Count'].fillna(0).astype(int)
df_long = df_long.reset_index(drop=True)

# Display the resulting DataFrame and save it to a new Excel file
df_long.info()
print(df_long.head())
df_long.to_excel('/content/drive/MyDrive/Colab Notebooks/Emigrants by Country 1981-2022/Cleaned_Emigrant_Data.xlsx', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            462 non-null    int64
 1   Country         462 non-null    object
 2   Emigrant_Count  462 non-null    int64
dtypes: int64(2), object(1)
memory usage: 11.0+ KB
   Year Country  Emigrant_Count
0  1981    USA*           40307
1  1982    USA*           44438
2  1983    USA*           34794
3  1984    USA*           34682
4  1985    USA*           38653